theme: jekyll-theme-cayman
title: Poster Session of the 2nd Computer Science Workshop @ DIBRIS
description: [A short description of your site's purpose]

html:
  comments:
    utterances:
      repo: "github-org/github-repo"
