theme: jekyll-theme-cayman
title: Poster Session of the 2nd Computer Science Workshop @ DIBRIS
description: [A short description of your site's purpose]
background-image: url('/Images/poster_session_2160x1080.png')

html:
  comments:
    utterances:
      repo: "github-org/github-repo"
